.TH "include Directory Reference" 3 "Thu Jan 12 2017" "Version 1.1.3" "Opus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBopus\&.h\fP"
.br
.RI "\fIOpus reference implementation API\&. \fP"
.ti -1c
.RI "file \fBopus_custom\&.h\fP"
.br
.RI "\fIOpus-Custom reference implementation API\&. \fP"
.ti -1c
.RI "file \fBopus_defines\&.h\fP"
.br
.RI "\fIOpus reference implementation constants\&. \fP"
.ti -1c
.RI "file \fBopus_multistream\&.h\fP"
.br
.RI "\fIOpus reference implementation multistream API\&. \fP"
.ti -1c
.RI "file \fBopus_types\&.h\fP"
.br
.RI "\fIOpus reference implementation types\&. \fP"
.in -1c
